src/main/resources/static/css/control.css
src/main/resources/static/css/login.css
src/main/resources/static/css/map.css
src/main/resources/static/js/i18n/en/index.properties
src/main/resources/static/js/i18n/zh-CN/index.properties
src/main/resources/static/js/lib/lodash.js
src/main/resources/static/js/utils/login.js
src/main/resources/static/js/utils/nodemap.js
src/main/resources/templates/html/control.html
src/main/resources/templates/html/login.html
src/main/resources/templates/html/map.html

add warn prompt

---

src/main/java/org/tron/explorer/controller/BlockController.java
src/main/java/org/tron/explorer/controller/CommController.java
src/main/java/org/tron/explorer/controller/GrpcClientController.java
src/main/java/org/tron/explorer/controller/TransferController.java
src/main/java/org/tron/explorer/controller/VoteWitnessController.java
src/main/java/org/tron/explorer/controller/WitnessController.java

remove useless interfaces and blank lines in web controllers

remove useless interfaces and blank lines

---

City.txt
src/main/java/org/tron/explorer/controller/AccountController.java
src/main/java/org/tron/walletserver/WalletClient.java

add updateAccount controller

---

src/main/java/org/tron/common/crypto/Hash.java
src/main/java/org/tron/common/crypto/Sha256Hash.java
src/main/java/org/tron/common/utils/TransactionUtils.java
src/main/java/org/tron/walletcli/Test.java
src/main/java/org/tron/walletserver/WalletClient.java

add Sha256Hash

---

src/main/java/org/tron/walletcli/TestClient.java

TestClient.java English Updates

---

src/main/java/org/tron/walletcli/TestClient.java

Also added a welcome banner to display instead of just "Input your Command"

More English updates

---

src/main/java/org/tron/common/utils/TransactionUtils.java
src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/TestClient.java
src/main/java/org/tron/walletserver/GrpcClient.java
src/main/java/org/tron/walletserver/WalletClient.java
src/main/protos/api/api.proto
src/main/protos/core/Contract.proto
src/main/protos/core/Tron.proto

add vm support

---

src/main/java/org/tron/walletcli/TestClient.java
src/main/java/org/tron/walletserver/WalletClient.java

correct cmd usage

---

src/main/java/org/tron/common/utils/Utils.java

use isEmpty instead of size

---

src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/TestClient.java
src/main/java/org/tron/walletserver/WalletClient.java
src/main/protos/core/Contract.proto
src/main/protos/core/Tron.proto

Remove account code hash

---

src/main/java/org/tron/walletcli/TestClient.java

fix bug for abi parameter split

fix bug for abi parameter split

---

src/main/java/org/tron/common/utils/AbiUtil.java

support array and negated value

Array coder

---

src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/TestClient.java
src/main/java/org/tron/walletserver/WalletClient.java

1. delete max_cpu/storage_usage paras when deploy/trigger contract
2. support multiple library when deploy contract

Add modifycontractpercent rpc

---

src/main/java/org/tron/walletserver/WalletClient.java

optimize libraryAddress delimiter

optimize libraryAddress delimiter

---

src/main/java/org/tron/common/utils/Utils.java

Add transaction receipt print

---

src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/TestClient.java
src/main/java/org/tron/walletserver/WalletClient.java
src/main/protos/core/Tron.proto

Print exception

---

src/main/java/org/tron/common/utils/AbiUtil.java
src/main/java/org/tron/walletcli/TestClient.java

encode constructor params

---

src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/walletcli/Client.java
src/main/protos/api/api.proto
src/main/protos/core/Contract.proto
src/main/protos/core/Tron.proto

Change storage fee

---

src/main/java/org/tron/test/Test.java

Added QWERTZ keyboard's

---

src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/walletserver/WalletApi.java

set indexed to ABI

---

src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletserver/GrpcClient.java
src/main/java/org/tron/walletserver/WalletApi.java
src/main/protos/api/api.proto

What does this PR do?
remove seteventfilter/seteventpluginconfig 
Why are these changes required?
set operations in wallet could  cause potential security problems
This PR has been tested by:
tested in local

remove seteventfilter/seteventpluginconfig for eventsubscribe

---

src/main/java/org/tron/common/utils/AbiUtil.java

Add address array coder

---

src/main/java/org/tron/common/utils/AbiUtil.java

AbiUtil error fix

---

src/main/java/org/tron/common/utils/AbiUtil.java

Fix dynamic coder

---

src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletserver/WalletApi.java

printTransaction miss ClearABIContract type

add ClearABIContract to printTransaction

---

src/main/java/org/tron/common/utils/AbiUtil.java

support parse `bytes[]` parameters

fix zero paraeter bug

---

src/main/java/org/tron/walletserver/WalletApi.java

print right contract address.
delete redundant transaction info.
support multi-signature with shielded transaction.

optional code

---

src/main/java/org/tron/walletcli/Client.java

improve tips message

---

README.md

1. Format ReadMe
2. add a cover for all subtitle so that user can easily navigate to what they want

Format ReadMe

---

README.md

1. polish readme
2. correct some mistake

correct mistake and polish readme

---

src/main/java/org/tron/walletserver/GrpcClient.java

This PR add the misssing  solidity interface.

fix the missing solidity interface

---

README.md

What does this PR do?
add a demo for scanning notes by ivk and ovk 
Why are these changes required?
add a demo for scanning notes by ivk and ovk
This PR has been tested by:
Manual Testing
Follow up
Extra details

add a demo for scanning notes

---

build.gradle

feat: update jline version

---

src/main/java/org/tron/common/utils/AbiUtil.java

parse bigInteger

---

README.md
src/main/java/org/tron/common/utils/AbiUtil.java

Fix Parse BigInteger 

---

src/main/java/org/tron/common/utils/AbiUtil.java
src/main/java/org/tron/walletcli/Client.java

fix cmd split bug

---

src/main/java/org/tron/common/utils/AbiUtil.java
src/main/java/org/tron/walletcli/Client.java

What does this PR do?
- 'DeployContract' supports big integers in constructor function.
- Optimize the input parameters of commands.
Why are these changes required?
This PR has been tested by:
Manual Testing
Follow up
Extra details

Optimize the input parameters 

---

src/main/protos/core/contract/market_contract.proto

typo: remove unused param for dex

typo: remove unused param

---

src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletserver/WalletApi.java
src/main/protos/core/contract/smart_contract.proto

update for solidity0.6.0

---

src/main/java/org/tron/walletcli/Client.java

Release v4.1.0.1

---

README.md
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletserver/GrpcClient.java
src/main/java/org/tron/walletserver/WalletApi.java
src/main/protos/api/api.proto
src/main/protos/core/contract/smart_contract.proto
src/main/resources/config.conf

Merge release 4.1.0 and 4.1.0.1 into develop.

Release 4.1.0.1 merged into develop

---

src/main/java/org/tron/demo/ShieldedTRC20Demo.java

shielded transfer demo

---

src/main/java/org/tron/demo/ShieldedTRC20Demo.java

refactor demo

---

src/main/java/org/tron/walletserver/WalletApi.java
src/main/protos/core/contract/smart_contract.proto

add `error` type and fix bug which get unrecognized type

---

src/main/java/org/tron/common/utils/JsonFormat.java

fix: do not print unknownfield

fix: do not print unknownfield

---

src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletserver/WalletApi.java
src/main/protos/api/api.proto
src/main/protos/core/contract/smart_contract.proto

Release 4.4.0 

---

src/main/protos/install-googleapis.sh

feat: update install-googleapis.sh to make it work

feat: update install-googleapis.sh to make it work

---

src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/GrpcClient.java
src/main/java/org/tron/walletserver/WalletApi.java
src/main/protos/api/api.proto
src/main/protos/install-googleapis.sh

merge release 4.5.2 to master

---

src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/GrpcClient.java
src/main/java/org/tron/walletserver/WalletApi.java
src/main/protos/api/api.proto
src/main/protos/core/Tron.proto
src/main/protos/core/contract/balance_contract.proto

feat(wallet-cli): new stake, add wallet-cli commands

feat(wallet-cli): new stake, add wallet-cli commands

---

src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/GrpcClient.java
src/main/java/org/tron/walletserver/WalletApi.java
src/main/protos/api/api.proto

Add three interfaces for the new stake model.
- Unit Tests
**Follow up**

feat(freezeV2): add three interfaces for the new stake model

---

src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/GrpcClient.java
src/main/java/org/tron/walletserver/WalletApi.java
src/main/protos/api/api.proto

add one interface for new stake model
- Unit Tests
**Follow up**

feat(new stake): add one interface for new stake model

---

README.md

add stake2.0 operation tips to README.md 
- Unit Tests
**Follow up**

add stake2.0 operation tips to README.md

---

src/main/java/org/tron/common/utils/HttpSelfFormatFieldName.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/WalletApi.java

add some param check
- Unit Tests
**Follow up**

add some param check

---

README.md
src/main/java/org/tron/walletcli/Client.java

fix some parameter verification problems
- Unit Tests
**Follow up**

fix some parameter verification problems

---

src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/GrpcClient.java
src/main/java/org/tron/walletserver/WalletApi.java
src/main/protos/api/api.proto
src/main/protos/core/Tron.proto
src/main/protos/core/contract/smart_contract.proto

Add dynamic energy related protocol buffer types and add estimate energy command.

feat(DynamicEnergy): add dynamic energy apis for wallet

---

src/main/java/org/tron/walletcli/Client.java

optimize estimate energy cmd parameters parse

feat(DynamicEnergy): optimize estimate energy cmd parameters parse

---

build.gradle

feat(zksnark): update zksnark

---

build.gradle
src/main/protos/api/api.proto
src/main/protos/core/Tron.proto
src/main/protos/core/contract/smart_contract.proto

1. modify api.proto
2. modify smart_contract.proto
3. modify Tron.proto

feat(stake): add new protobuf 

---

README.md
src/main/java/org/tron/common/utils/JsonFormat.java
src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/WalletApi.java

1.fix address parse BUG in Protocol.TransactionInfo.Log.address
2.Use a fixed password when transactions occur

add custom variable feature

---

README.md
src/main/java/org/tron/walletcli/Client.java

fix json string issue in variable

fix json string issue in variable

---

src/main/protos/core/Tron.proto

optimize resource usage recovery logic
optimize resource usage recovery logic
- Unit Tests
**Follow up**

fix(freezeV2): optimize resource usage recovery logic

---

README.md

update GenerateAddress api
- Unit Tests
**Follow up**

feat(readme): update GenerateAddress api

---

src/main/java/org/tron/common/utils/HttpSelfFormatFieldName.java

revert address encoding mapping
- Unit Tests
**Follow up**

fix(wallet-cli): revert address encoding mapping

---

README.md
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/GrpcClient.java
src/main/java/org/tron/walletserver/WalletApi.java

close, https://github.com/tronprotocol/wallet-cli/issues/666

feat(api): synchronize new interfaces of java-tron

---

build.gradle

- update protobufVersion from 3.21.12 to 3.25.5
- Unit Tests
**Follow up**

feat(dependency): update protobufVersion to 3.25.5

---

.gitignore
README.md
build.gradle
src/main/java/org/tron/common/utils/AbiUtil.java
src/main/java/org/tron/demo/ECKeyDemo.java
src/main/java/org/tron/mnemonic/Mnemonic.java
src/main/java/org/tron/mnemonic/MnemonicFile.java
src/main/java/org/tron/mnemonic/MnemonicUtils.java
src/main/java/org/tron/test/Test.java
src/main/java/org/tron/trident/TridentQueryWrapper.java
src/main/java/org/tron/trident/TridentUtil.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/WalletApi.java
src/main/resources/config.conf

feat(mnemonics):add mnemonics

---

src/main/java/org/tron/mnemonic/MnemonicUtils.java

feat(mnemonic): mnemonic file name

---

src/main/java/org/tron/mnemonic/MnemonicUtils.java
src/main/java/org/tron/walletserver/WalletApi.java

update mnemonic file when changepwd

feat(mnemonic): update mnemonic file when changepwd

---

src/main/java/org/tron/mnemonic/MnemonicUtils.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/WalletApi.java

feat(mnemonic): add select mnemonic file

---

src/main/java/org/tron/mnemonic/MnemonicUtils.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java

feat(mnemonic): optimize mnemonic tips

---

src/main/java/org/tron/keystore/WalletUtils.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletserver/WalletApi.java

feat(mnemonic): rewrite keystore file

---

.gitignore
src/main/java/org/tron/walletcli/WalletApiWrapper.java

import wallet clean mnemonic file

feat(mnemonic): import wallet clean mnemonic file

---

src/main/java/org/tron/walletcli/Client.java

feat(mnemonic): optimize import wallet tips

---

build.gradle

feat(mnemonic): upgrade web3j version

---

.gitignore
build.gradle
src/main/java/org/tron/mnemonic/MnemonicUtils.java
src/main/java/org/tron/mnemonic/SubAccount.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java

feat(mnemonic): support generate subaccount

---

src/main/java/org/tron/keystore/ClearWalletUtils.java
src/main/java/org/tron/keystore/WalletUtils.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/WalletApi.java

add command:clear wallet keystore

feat(keystore)：add command:clear wallet keystore

---

src/main/java/org/tron/mnemonic/MnemonicUtils.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/WalletApi.java

feat(mnemonic): support 24 mnemonic words

---

src/main/java/org/tron/ledger/LedgerSignUtil.java
src/main/java/org/tron/ledger/listener/LedgerEventListener.java
src/main/java/org/tron/ledger/sdk/ApduMessageBuilder.java
src/main/java/org/tron/ledger/sdk/CommonUtil.java
src/main/java/org/tron/ledger/wrapper/LedgerUserHelper.java
src/main/java/org/tron/walletserver/WalletApi.java

support AccountPermissionUpdateContract for Ledger.

fix(transaction): support AccountPermissionUpdateContract for Ledger

---

src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/keystore/ClearWalletUtils.java
src/main/java/org/tron/keystore/WalletFile.java
src/main/java/org/tron/keystore/WalletUtils.java
src/main/java/org/tron/ledger/LedgerSignUtil.java
src/main/java/org/tron/ledger/console/TronLedgerImportAccount.java
src/main/java/org/tron/ledger/listener/BaseListener.java
src/main/java/org/tron/ledger/listener/LedgerEventListener.java
src/main/java/org/tron/mnemonic/SubAccount.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/WalletApi.java

support multiple signatures for Ledger

fix(transaction): support multiple signatures for Ledger

---

src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/core/zen/ShieldedTRC20Wrapper.java
src/main/java/org/tron/core/zen/ShieldedWrapper.java
src/main/java/org/tron/demo/ShieldedTRC20Demo.java
src/main/java/org/tron/keystore/ClearWalletUtils.java
src/main/java/org/tron/ledger/LedgerAddressUtil.java
src/main/java/org/tron/ledger/LedgerFileUtil.java
src/main/java/org/tron/ledger/LedgerSignUtil.java
src/main/java/org/tron/ledger/TronLedgerGetAddress.java
src/main/java/org/tron/ledger/console/TronLedgerImportAccount.java
src/main/java/org/tron/mnemonic/MnemonicUtils.java
src/main/java/org/tron/mnemonic/SubAccount.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/WalletApi.java

support selecting ledger when importWalletByLedger

fix(Ledger): support selecting ledger when importWalletByLedger

---

README.md
src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/keystore/ClearWalletUtils.java
src/main/java/org/tron/mnemonic/SubAccount.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/WalletApi.java

optimize prompt information and user experience

fix(information): optimize prompt information and user experience

---

README.md
src/main/java/org/tron/keystore/ClearWalletUtils.java
src/main/java/org/tron/ledger/TronLedgerGetAddress.java
src/main/java/org/tron/mnemonic/SubAccount.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java

Optimize prompt information and improve README.md.

fix(info & README): optimize prompt information and improve README.md

---

README.md
src/main/java/org/tron/ledger/LedgerAddressUtil.java
src/main/java/org/tron/ledger/LedgerConst.java
src/main/java/org/tron/ledger/LedgerSignUtil.java
src/main/java/org/tron/ledger/wrapper/LedgerUserHelper.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java

optimize the user experience of Ledger and README.md.

fix(Ledger & README): optimize the user experience of Ledger and README.md

---

src/main/resources/config.conf

Optimize configuration instructions.

fix(conf): optimize configuration instructions

---

src/main/java/org/tron/common/utils/DomainValidator.java
src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/gasfree/GasFreeApi.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/GrpcClient.java
src/main/java/org/tron/walletserver/WalletApi.java

feat(cmd): optimize information display

---

README.md

remove abandoned badges for readme

feat(doc): remove abandoned badges for readme

---

README.md
src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/walletcli/ApiClientFactory.java
src/main/java/org/tron/walletcli/Client.java
src/main/resources/commands.txt
src/main/resources/help_summary.txt

feat(prompt): optimize prompt information

---

src/main/java/org/tron/walletserver/ApiClient.java

Support single node configuration.

feat(single-node): support single node configuration

---

README.md
src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/WalletApi.java
src/main/resources/config.conf
src/main/resources/help_summary.txt

feat(help): optimize help prompt

---

README.md
src/main/resources/config.conf

Remove obsolete configurations.

feat(conf): remove obsolete configurations

---

src/main/java/org/tron/common/utils/JsonFormat.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletserver/WalletApi.java

fix some minor issues in comments

chore: fix some minor issues in comments

---

README.md
src/main/java/org/tron/common/utils/Utils.java
src/main/java/org/tron/core/dao/BackupRecord.java
src/main/java/org/tron/core/dao/Tx.java
src/main/java/org/tron/core/manager/BackupRecordManager.java
src/main/java/org/tron/core/manager/TxHistoryManager.java
src/main/java/org/tron/core/viewer/BackupRecordsViewer.java
src/main/java/org/tron/core/viewer/TxHistoryViewer.java
src/main/java/org/tron/keystore/WalletUtils.java
src/main/java/org/tron/ledger/sdk/LedgerProtocol.java
src/main/java/org/tron/mnemonic/SubAccount.java
src/main/java/org/tron/walletcli/Client.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/WalletApi.java
src/main/resources/commands.txt
src/main/resources/config.conf
src/main/resources/help_summary.txt

Optimize the wallet user experience.

feat(wallet): optimize the wallet user experience

---

src/main/java/org/tron/core/viewer/BackupRecordsViewer.java
src/main/java/org/tron/walletcli/WalletApiWrapper.java
src/main/java/org/tron/walletserver/WalletApi.java

feat(backup): optimize backup records
